spring:
  application:
    name: event-logger

  datasource:
    url: jdbc:sqlserver://localhost:1433;databaseName=event_logger;encrypt=true;trustServerCertificate=true
    username: sa
    password: Password123@
    driver-class-name: com.microsoft.sqlserver.jdbc.SQLServerDriver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.SQLServerDialect

  kafka:
    bootstrap-servers: localhost:9092
    consumer:
      group-id: event-logger-group
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer

app:
  jwt:
    secret: SecretKeyEventLogger#123321456654789987
    expiration: 86400000
  kafka:
    topic: event-logs

springdoc:
  swagger-ui:
    oauth:
      client-id:
      client-secret:
      use-pkce-with-authorization-code-grant: false
      scopes:
    disable-swagger-default-url: true
